export interface Product {
  id: string;
  name: string;
  category: "gaming" | "laptop" | "office" | "workstation";
  categoryLabel: string;
  specs: string[];
  description: string;
  buyPrice: number;
  rentPrice: number;
  image: string;
  tags: string[];
  badge?: "hot" | "new" | "sale";
}

export const categories = [
  { id: "all", label: "ทั้งหมด", icon: "🖥️" },
  { id: "gaming", label: "เกมมิ่ง", icon: "🎮" },
  { id: "laptop", label: "แล็ปท็อป", icon: "💻" },
  { id: "office", label: "สำนักงาน", icon: "🏢" },
  { id: "workstation", label: "เวิร์คสเตชั่น", icon: "⚙️" },
];

export const products: Product[] = [
  {
    id: "gm-001",
    name: "I-Kom TITAN X",
    category: "gaming",
    categoryLabel: "เกมมิ่ง",
    specs: [
      "Intel Core i9-14900K",
      "RTX 4090 24GB",
      "64GB DDR5 RAM",
      "2TB NVMe SSD",
    ],
    description: "เครื่องเกมมิ่งระดับท็อปสำหรับเกมเมอร์ที่ต้องการความแรงสูงสุด เล่นเกม AAA ได้ลื่นที่ 4K Ultra",
    buyPrice: 129900,
    rentPrice: 6990,
    image: "/gaming-desktop.png",
    tags: ["4K Gaming", "Streaming", "VR Ready"],
    badge: "hot",
  },
  {
    id: "gm-002",
    name: "I-Kom FURY PRO",
    category: "gaming",
    categoryLabel: "เกมมิ่ง",
    specs: [
      "Intel Core i7-14700K",
      "RTX 4070 Ti 12GB",
      "32GB DDR5 RAM",
      "1TB NVMe SSD",
    ],
    description: "เครื่องเกมมิ่งระดับกลาง-สูง คุ้มค่าที่สุดสำหรับเกมเมอร์จริงจัง เล่นได้ทุกเกมที่ 1440p Ultra",
    buyPrice: 69900,
    rentPrice: 3990,
    image: "/gaming-desktop.png",
    tags: ["1440p Gaming", "Streaming"],
    badge: "new",
  },
  {
    id: "gm-003",
    name: "I-Kom BLAZE",
    category: "gaming",
    categoryLabel: "เกมมิ่ง",
    specs: [
      "AMD Ryzen 7 7800X3D",
      "RTX 4060 Ti 8GB",
      "16GB DDR5 RAM",
      "512GB NVMe SSD",
    ],
    description: "เครื่องเกมมิ่งระดับเริ่มต้นที่นิยมเยอะที่สุด เล่นเกมลื่นๆ ได้ เหมาะสำหรับ 1080p High-Ultra",
    buyPrice: 35900,
    rentPrice: 1990,
    image: "/gaming-desktop.png",
    tags: ["1080p Gaming", "ประหยัด"],
    badge: "sale",
  },
  {
    id: "lt-001",
    name: "I-Kom SWIFT 16",
    category: "laptop",
    categoryLabel: "แล็ปท็อป",
    specs: [
      "Intel Core i7-13700H",
      "RTX 4060 8GB",
      "16GB DDR5 RAM",
      "512GB NVMe SSD",
    ],
    description: "แล็ปท็อปเกมมิ่งบางเบา จอ 16 นิ้ว 165Hz พกพาสะดวก เล่นเกมได้ ทำงานได้ดี",
    buyPrice: 42900,
    rentPrice: 2490,
    image: "/laptop.png",
    tags: ["พกพาง่าย", "จอ 165Hz"],
    badge: "hot",
  },
  {
    id: "lt-002",
    name: "I-Kom AIR 14",
    category: "laptop",
    categoryLabel: "แล็ปท็อป",
    specs: [
      "Intel Core i5-1340P",
      "Intel Iris Xe",
      "16GB DDR5 RAM",
      "512GB NVMe SSD",
    ],
    description: "แล็ปท็อปบางเบาสุดน้ำหนักไม่ถึง 1.3 กก. แบตอึด 12 ชม. เหมาะสำหรับทำงานและเรียน",
    buyPrice: 27900,
    rentPrice: 1490,
    image: "/laptop.png",
    tags: ["บางเบา", "แบตอึด"],
    badge: "new",
  },
  {
    id: "lt-003",
    name: "I-Kom PRO 15",
    category: "laptop",
    categoryLabel: "แล็ปท็อป",
    specs: [
      "Apple M3 Pro",
      "18GB Unified RAM",
      "512GB SSD",
      "จอ Retina 15.3 นิ้ว",
    ],
    description: "แล็ปท็อประดับพรีเมียม ประสิทธิภาพสูง เหมาะสำหรับครีเอเตอร์ ตัดต่อวิดีโอ ทำกราฟิก",
    buyPrice: 59900,
    rentPrice: 3290,
    image: "/laptop.png",
    tags: ["ครีเอเตอร์", "ตัดต่อวิดีโอ"],
  },
  {
    id: "of-001",
    name: "I-Kom OFFICE PRO",
    category: "office",
    categoryLabel: "สำนักงาน",
    specs: [
      "Intel Core i5-14400",
      "Intel UHD 730",
      "16GB DDR5 RAM",
      "512GB NVMe SSD",
    ],
    description: "คอมสำนักงานที่ตอบโจทย์ทุกการทำงาน Office, ประชุม Zoom, เปิดเว็บหลายแท็บลื่นไหล",
    buyPrice: 18900,
    rentPrice: 990,
    image: "/office-desktop.png",
    tags: ["ทำงาน", "Office"],
    badge: "sale",
  },
  {
    id: "of-002",
    name: "I-Kom OFFICE LITE",
    category: "office",
    categoryLabel: "สำนักงาน",
    specs: [
      "Intel Core i3-14100",
      "Intel UHD 730",
      "8GB DDR5 RAM",
      "256GB NVMe SSD",
    ],
    description: "คอมสำนักงานราคาประหยัด เหมาะสำหรับงานเอกสาร เปิดเว็บ ใช้งานทั่วไป คุ้มค่าที่สุด",
    buyPrice: 12900,
    rentPrice: 690,
    image: "/office-desktop.png",
    tags: ["ประหยัด", "ใช้งานทั่วไป"],
  },
  {
    id: "of-003",
    name: "I-Kom OFFICE MAX",
    category: "office",
    categoryLabel: "สำนักงาน",
    specs: [
      "Intel Core i7-14700",
      "Intel UHD 770",
      "32GB DDR5 RAM",
      "1TB NVMe SSD",
    ],
    description: "คอมสำนักงานระดับสูงสำหรับงานที่ต้องใช้แรมเยอะ เปิดโปรแกรมพร้อมกันหลายตัว มัลติทาสก์ลื่น",
    buyPrice: 29900,
    rentPrice: 1590,
    image: "/office-desktop.png",
    tags: ["มัลติทาสก์", "แรมเยอะ"],
    badge: "new",
  },
  {
    id: "ws-001",
    name: "I-Kom CREATOR X",
    category: "workstation",
    categoryLabel: "เวิร์คสเตชั่น",
    specs: [
      "AMD Threadripper 7970X",
      "RTX 4000 Ada 20GB",
      "128GB DDR5 ECC RAM",
      "4TB NVMe SSD",
    ],
    description: "เวิร์คสเตชั่นระดับมืออาชีพสำหรับ 3D Rendering, VFX, สถาปนิก รองรับงานหนักทุกรูปแบบ",
    buyPrice: 259900,
    rentPrice: 12990,
    image: "/workstation.png",
    tags: ["3D Rendering", "VFX"],
    badge: "hot",
  },
  {
    id: "ws-002",
    name: "I-Kom STUDIO PRO",
    category: "workstation",
    categoryLabel: "เวิร์คสเตชั่น",
    specs: [
      "Intel Xeon W5-3435X",
      "RTX A5000 24GB",
      "64GB DDR5 ECC RAM",
      "2TB NVMe SSD",
    ],
    description: "เวิร์คสเตชั่นสำหรับงาน CAD/CAM, จำลองวิศวกรรม, AI/ML Development ความเสถียรระดับสูง",
    buyPrice: 189900,
    rentPrice: 9990,
    image: "/workstation.png",
    tags: ["CAD/CAM", "AI/ML"],
  },
  {
    id: "ws-003",
    name: "I-Kom DATA PRO",
    category: "workstation",
    categoryLabel: "เวิร์คสเตชั่น",
    specs: [
      "AMD EPYC 9354",
      "RTX 4090 24GB",
      "256GB DDR5 ECC RAM",
      "8TB NVMe RAID",
    ],
    description: "เวิร์คสเตชั่นสำหรับ Data Science, Deep Learning, Big Data Processing รองรับ Dataset ขนาดใหญ่",
    buyPrice: 399900,
    rentPrice: 19990,
    image: "/workstation.png",
    tags: ["Deep Learning", "Big Data"],
    badge: "new",
  },
];

export function formatPrice(price: number): string {
  return price.toLocaleString("th-TH");
}
